In [8]:
import numpy as nb
class DataAnalytics:
    def __init__(self):
        self.data = None
    def __check(self):
        """
        Private method to check data.
        """
        if self.data is None:
            print("Make array first!")
            return True
        return False
    def show(self):
        """
        Normal method to print name.
        """
        print("DataAnalytics class is running")
    def create(self):
        """
        Method to create numpy array.
        """
        print("1 for 1D")
        print("2 for 2D")
        print("3 for 3D")
        choice = input("Enter choice: ")
        text = input("Enter numbers separated by space: ")

        words = text.split()
        numbers = []
        for word in words:
            numbers.append(int(word))
        
        if choice == "1":
            self.data = nb.array(numbers)
            print("Array created:\n", self.data)
            
            print("1 for Indexing")
            print("2 for Slicing")
            action = input("Enter choice: ")
            if action == "1":
                index = int(input("Enter index: "))
                print(self.data[index])
            if action == "2":
                start = int(input("Enter start: "))
                end = int(input("Enter end: "))
                print(self.data[start:end])
                
        elif choice == "2":
            rows = int(input("Enter rows: "))
            cols = int(input("Enter columns: "))
            self.data = nb.array(numbers).reshape(rows, cols)
            print("Array created:\n", self.data)
            
        elif choice == "3":
            blocks = int(input("Enter blocks: "))
            rows = int(input("Enter rows: "))
            cols = int(input("Enter columns: "))
            self.data = nb.array(numbers).reshape(blocks, rows, cols)
            print("Array created:\n", self.data)

    def maths(self):
        """
        Method to do simple maths using numpy easy functions.
        """
        if self.__check():
            return
        print("1 for Add")
        print("2 for Subtract")
        print("3 for Multiply")
        print("4 for Divide")
        choice = input("Enter choice: ")
    
        text = input("Enter second array numbers: ")
        words = text.split()
        numbers = []
        for word in words:
            numbers.append(int(word))
            
        second = nb.array(numbers).reshape(self.data.shape)
        if choice == "1":
            print(nb.add(self.data, second))
        elif choice == "2":
            print(nb.subtract(self.data, second))
        elif choice == "3":
            print(nb.multiply(self.data, second))
        elif choice == "4":
            print(nb.divide(self.data, second))

    def split_combine(self):
        """
        Method to combine and split.
        """
        if self.__check():
            return
            
        print("1 to Combine")
        print("2 to Split")
        choice = input("Enter choice: ")
        
        if choice == "1":
            text = input("Enter numbers to combine: ")
            words = text.split()
            numbers = []
            for word in words:
                numbers.append(int(word))
                
            second = nb.array(numbers).reshape(self.data.shape)
            print(nb.concatenate((self.data, second)))
            
        elif choice == "2":
            parts = int(input("Enter how many parts: "))
            print(nb.array_split(self.data, parts))

    def search_filter(self):
        """
        Method to search, sort, filter using basic numpy functions.
        """
        if self.__check():
            return
            
        print("1 to Search")
        print("2 to Sort")
        print("3 to Filter")
        choice = input("Enter choice: ")
        
        if choice == "1":
            target = int(input("Enter value: "))
            print(nb.where(self.data == target))
        elif choice == "2":
            print(nb.sort(self.data))
        elif choice == "3":
            limit = int(input("Enter minimum: "))
            print(self.data[self.data > limit])

    def statistics(self):
        """
        Method to find simple statistics using easy numpy functions.
        """
        if self.__check():
            return
            
        print("1 Sum")
        print("2 Mean (Average)")
        print("3 Minimum")
        print("4 Maximum")
        choice = input("Enter choice: ")
        
        if choice == "1":
            print("Sum is:", nb.sum(self.data))
        elif choice == "2":
            print("Mean is:", nb.mean(self.data))
        elif choice == "3":
            print("Minimum is:", nb.min(self.data))
        elif choice == "4":
            print("Maximum is:", nb.max(self.data))


In [12]:
student = DataAnalytics()
student.show()

while True:
    print("Welcome to the NumPy Analyzer")
    print("Choose an option:")
    print("1 Create Array")
    print("2 Math Operations")
    print("3 Combine or Split")
    print("4 Search Sort Filter")
    print("5 Statistics")
    print("6 Exit")
    
    main = input("Enter your choice: ")
    if main == "1":
        student.create()
    if main == "2":
        student.maths()
    if main == "3":
        student.split_combine()
    if main == "4":
        student.search_filter()
    if main == "5":
        student.statistics()
    if main == "6":
        print(DataAnalytics.__doc__)
        print(student.__init__.__doc__)
        print(student._DataAnalytics__check.__doc__)
        print(DataAnalytics.show.__doc__)
        print(student.create.__doc__)
        print(student.maths.__doc__)
        print(student.split_combine.__doc__)
        print(student.search_filter.__doc__)
        print(student.statistics.__doc__)
        print("Goodbyeeeee")
        break

DataAnalytics class is running
Welcome to the NumPy Analyzer
Choose an option:
1 Create Array
2 Math Operations
3 Combine or Split
4 Search Sort Filter
5 Statistics
6 Exit
1 for 1D
2 for 2D
3 for 3D
Array created:
 [10 20 30 40 50]
1 for Indexing
2 for Slicing
40
Welcome to the NumPy Analyzer
Choose an option:
1 Create Array
2 Math Operations
3 Combine or Split
4 Search Sort Filter
5 Statistics
6 Exit
1 for 1D
2 for 2D
3 for 3D
Array created:
 [21 22 23 24 25]
1 for Indexing
2 for Slicing
[21 22 23]
Welcome to the NumPy Analyzer
Choose an option:
1 Create Array
2 Math Operations
3 Combine or Split
4 Search Sort Filter
5 Statistics
6 Exit
1 for Add
2 for Subtract
3 for Multiply
4 for Divide
[31 34 36 38 40]
Welcome to the NumPy Analyzer
Choose an option:
1 Create Array
2 Math Operations
3 Combine or Split
4 Search Sort Filter
5 Statistics
6 Exit
1 Sum
2 Mean (Average)
3 Minimum
4 Maximum
Mean is: 23.0
Welcome to the NumPy Analyzer
Choose an option:
1 Create Array
2 Math Operations
3 Com